server:
  port: 8081
spring:
  application:
    name: springboot-mongo-angular
  data:
    mongodb:
      #      host: localhost
      #      port: 27017
      #      uri: mongodb://user:secret@mongo1.example.com:12345,mongo2.example.com:23456/test
      #      uri: mongodb://localhost:27017/blog
      host: localhost
      port: 27017
      database: spring_mongo
      grid-fs-database: images

logging:
  level:
    com.example: DEBUG
    org.springframework.web: DEBUG