server:
  port: 8080
spring:
  application:
    name: springboot-mongo-angular
  data:
    mongodb:
      host: localhost
      port: 27017
      database: spring_mongo
      grid-fs-database: images
      repositories:
        type: auto

logging:
  level:
    com.example: DEBUG
    org.springframework.web: DEBUG